export const CLOSE_POPUP = 'CLOSE_POPUP';
export const SELECT_COLUMN = 'SELECT_COLUMN';
export const INCREMENT_MOVES_COUNTER = 'INCREMENT_MOVES_COUNTER';
export const DID_WRONG_MOVE = 'DID_WRONG_MOVE';
export const RESET_GAME = 'RESET_GAME';
export const SHOW_POPUP_VICTORY = 'SHOW_POPUP_VICTORY';
